Developed gui interface
Fedya001/sorted-knapsack-java-exercise pull request #1
Opened 2019-10-20 12:01 UTC by Fedya001

2019-10-21 21:01 UTC, aygolovach requested changes
Отлично организован код ui-части приложения, хорошее решение с выносом повторяющихся методов в класс WondowToolkit

2019-10-21 21:01 UTC, aygolovach commented on src/com/fedya/utils/WindowToolkit.java
> +  public static void MoveToCenter(Window window) {
Я просто обязан придраться к именованию с большой буквы

2019-10-21 21:01 UTC, aygolovach commented on src/com/fedya/knapsack/SortedKnapsack.java
> +    shapes.remove(shape);
Не уменьшается объем занятого пространства

2019-10-22 15:06 UTC, Fedya001 commented on src/com/fedya/utils/WindowToolkit.java
> +  public static void MoveToCenter(Window window) {
Ой, да, спасибо, это привычка от google C++ codestyle :)

2019-10-22 20:35 UTC, aygolovach approved these changes

2019-10-22 20:36 UTC, merged